"""add conversation embeddings table

Revision ID: ca49e3c1beea
Revises: f3589670f9a9
Create Date: 2026-03-13 16:49:37.603062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca49e3c1beea'
down_revision = 'f3589670f9a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ticket_id', sa.String(length=50), nullable=True),
    sa.Column('ticket_type', sa.String(length=20), nullable=True),
    sa.Column('platform', sa.String(length=10), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_embeddings_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_embeddings_session_id'))

    op.drop_table('conversation_embeddings')
    # ### end Alembic commands ###
